spring:
  application:
    name: mcp-server

  main:
    banner-mode: OFF

  ai:
    mcp:
      server:
        stdio: true
        capabilities:
          completion: false
          prompt: false
          resource: false

# disabling logging for STDOUT because breaks JSON-RPC STDIO communication
logging:
  pattern:
    console: